[package]
name = "mmb"
version = "0.1.0"
authors = ["Evgeny Khudoba <evgeny.khudoba@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4.19"
log = "0.4.11"
fern = "0.6.0"
itertools = "0.10.0"
bytes = "1.0"

serde = { version = "^1", features = ["derive"]}
serde_json = "1.0"

tokio = { version = "1.0", features = ["macros"]}

actix = "0.11.0-beta.1"
actix-codec = "0.4.0-beta.1"
actix-web = { version = "4.0.0-beta.1", features = ["rustls"]}
actix-web-actors = "4.0.0-beta.1"

awc = "3.0.0-beta.1"

futures = "0.3.9"
async-channel = "1.5.1"

smallstr = { version = "0.2.0", features = ["serde"]}

[dev-dependencies]
actix-rt = "2.0.0-beta.2"
