[package]
name = "mmb"
version = "0.1.0"
authors = ["Evgeny Khudoba <evgeny.khudoba@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "0.4.11"
serde = { version = "^1", features = ["derive"]}
serde_json = "^1"

smallstr = { version = "0.2.0", features = ["serde"]}

tokio = "^0.3"
hyper = { version = "0.14.1", features = ["http1", "client"]}
hyper-tls = "0.5.0"

tungstenite = { version = "0.11.1", features = ["tls"]}
