[package]
name = "mmb"
version = "0.1.0"
authors = ["Evgeny Khudoba <evgeny.khudoba@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "0.8", features = ["serde", "v4"]}

lazy_static = "1.4.0"

dashmap = "4"
chrono = { version = "0.4", features = ["serde"]}
log = "0.4"
fern = "0.6"
itertools = "0.10"
bytes = "1"
regex = "1"
toml = "0.5"

serde = { version = "1", features = ["derive", "rc"]}
serde_json = "1"

parking_lot = { version = "0.11", features = ["serde"]}

tokio = { version = "1", features = ["macros", "time", "sync", "rt"]}

actix = "0.12"
actix-codec = "0.4"
actix-web = { version = "4.0.0-beta.8", features = ["rustls"]}
actix-web-actors = "4.0.0-beta.6"

libc = "0.2"
awc = "3.0.0-beta.7"
form_urlencoded = "1"
hyper-tls = "0.5"
hyper = { version = "0.14", features = ["http1", "runtime", "client", "tcp"] }

futures = "0.3"

smallstr = { version = "0.2", features = ["serde"]}

anyhow = "1"
rust_decimal = { version = "1" , features = ["maths"]}
rust_decimal_macros = "1"
derive-getters = "0.2"

async-trait = "0.1"
hmac = "0.11"
crypto-mac = { version = "0.11", features = ["std"]}
sha2 = "0.9"
hex = "0.4"

enum-map = "1.1.1"
nanoid = "0.4.0"

scopeguard = "1.1.0"
once_cell = "1.8.0"

mockall_double = "0.2.0"

[dev-dependencies]
rand = "0.8"
actix-rt = "2"
pretty_assertions = "0.7"
rstest = "0.10"
mockall = "0.10.2"
once_cell = "1.8.0"

[lib]
name = "mmb_lib"
path = "src/lib.rs"
