[package]
name = "mmb"
version = "0.1.0"
authors = ["Evgeny Khudoba <evgeny.khudoba@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "0.8", features = ["serde"]}

dashmap = "4"
chrono = { version = "0.4", features = ["serde"]}
log = "0.4.11"
fern = "0.6.0"
itertools = "0.10.0"
bytes = "1.0"
regex = "1"

serde = { version = "^1", features = ["derive", "rc"]}
serde_json = "1.0"

parking_lot = { version = "0.11", features = ["serde"]}

tokio = { version = "1.0", features = ["macros"]}

actix = "0.11.0-beta.1"
actix-codec = "0.4.0-beta.1"
actix-web = { version = "4.0.0-beta.1", features = ["rustls"]}
actix-web-actors = "4.0.0-beta.1"

awc = "3.0.0-beta.1"

futures = "0.3"
async-channel = "1.5.1"

smallstr = { version = "0.2.0", features = ["serde"]}

anyhow = "1.0.38"
rust_decimal = "1.10.0"
rust_decimal_macros = "1.10.1"
derive-getters = "0.2.0"

async-trait = "0.1.42"

[dev-dependencies]
actix-rt = "2.0.0-beta.2"
pretty_assertions = "0.6"

[lib]
name = "mmb_lib"
path = "src/lib.rs"
