[package]
name = "mmb_core"
version = "0.1.0"
authors = ["Evgeny Khudoba <evgeny.khudoba@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "0.8", features = ["serde", "v4"]}

dashmap = "4"
chrono = { version = "0.4", features = ["serde"]}
log = "0.4"
fern = "0.6"
itertools = "0.10"
bytes = "1"
regex = "1"
toml_edit = { version = "0.10", features = ["serde"] }

serde = { version = "1", features = ["derive", "rc"]}
serde_json = "1"

parking_lot = { version = "0.11", features = ["serde"]}

tokio = { version = "1", features = ["macros", "time", "sync", "rt", "signal"]}

jsonrpc-core = "18.0.0"
jsonrpc-ipc-server = "18.0.0"

actix = "0.12"
actix-codec = "0.4"
actix-http = "=3.0.0-beta.13"
actix-web-actors = "=4.0.0-beta.7"
actix-web = { version = "=4.0.0-beta.12", features = ["rustls"]}
awc = { version = "=3.0.0-beta.11", features = ["rustls"]}

libc = "0.2"
form_urlencoded = "1"
hyper-tls = "0.5"
hyper = { version = "0.14", features = ["http1", "runtime", "client", "tcp"] }

futures = "0.3"

smallstr = { version = "0.2", features = ["serde"]}

anyhow = "1"
thiserror = "1"
rust_decimal = { version = "1", features = ["maths"]}
rust_decimal_macros = "1"

async-trait = "0.1"
hmac = "0.11"
crypto-mac = { version = "0.11", features = ["std"]}
sha2 = "0.9"
hex = "0.4"

enum-map = "1.1.1"

scopeguard = "1.1"
once_cell = "1.8"

mockall_double = "0.2"
paste = "1"

mmb_rpc = { path = "../mmb_rpc" }

[dev-dependencies]
rand = "0.8"
actix-rt = "2"
pretty_assertions = "1"
rstest = "0.10"
mockall = "0.10.2"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc"] }