[strategy]
test_value = false

[core]
[[core.exchanges]]

is_margin_trading = false
web_socket_host = ""
web_socket2_host = ""
rest_host = ""
websocket_channels = [ "depth20" ]
subscribe_to_market_data = true

[core.exchanges.exchange_account_id]
exchange_id = "Binance"
account_number = 0

[[core.exchanges.currency_pairs]]
base = "phb"
quote = "btc"

[[core.exchanges.currency_pairs]]
base = "eth"
quote = "btc"

[[core.exchanges.currency_pairs]]
base = "eos"
quote = "btc"
