[strategy]
spread = 3

[[core.exchanges]]
exchange_account_id = "Binance0"
is_margin_trading = false
request_trades = false
websocket_channels = ["depth20"]
subscribe_to_market_data = true

currency_pairs = [ { base = "cnd", quote = "btc"  },
                   { base = "eth", quote = "btc"  },
                   { base = "eos", quote = "btc"  } ]
