[[core.exchanges]]
exchange_account_id = "Binance0"
is_margin_trading = false
rest_host = ""
subscribe_to_market_data = true
web_socket2_host = ""
web_socket_host = ""
websocket_channels = ["depth20"]

[[core.exchanges.currency_pairs]]
base = "phb"
quote = "btc"

[[core.exchanges.currency_pairs]]
base = "eth"
quote = "btc"

[[core.exchanges.currency_pairs]]
base = "eos"
quote = "btc"

[strategy]
