[package]
name = "serum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
awc = { version = "=3.0.0-beta.11", features = ["rustls"]}

dashmap = "4"

mmb_core = { path = "../../core/" }
mmb_utils = { path = "../../mmb_utils" }

tokio = { version = "1" }